### ISSUE TITLE
Endpoint checklist

### ISSUE THREAD

**Issue by Kegsay** [matrix-org/gomatrix#9]
This issue is tracking which endpoints need to be added to gomatrix. It's 

### API Standards
- [ ] GET /_matrix/client/versions

### Account registration and management
- [x] POST /_matrix/client/r0/register
- [ ] POST /_matrix/client/r0/account/password/email/requestToken
- [ ] POST /_matrix/client/r0/account/deactivate
- [ ] POST /_matrix/client/r0/account/password
- [ ] POST /_matrix/client/r0/register/email/requestToken

### Filtering
- [ ] GET /_matrix/client/r0/user/{userId}/filter/{filterId}
- [ ] POST /_matrix/client/r0/user/{userId}/filter

### Syncing
- [x] GET /_matrix/client/r0/sync

### Sending events to a room
- [ ] PUT /_matrix/client/r0/rooms/{roomId}/state/{eventType}
- [ ] PUT /_matrix/client/r0/rooms/{roomId}/state/{eventType}/{stateKey}
- [ ] PUT /_matrix/client/r0/rooms/{roomId}/send/{eventType}/{txnId}

### Redactions
- [ ] PUT /_matrix/client/r0/rooms/{roomId}/redact/{eventId}/{txnId}

### Rooms
- [ ] POST /_matrix/client/r0/createRoom
- [ ] PUT /_matrix/client/r0/rooms/{roomId}/typing/{userId}

### Room Aliases
- [ ] PUT /_matrix/client/r0/directory/room/{roomAlias}
- [ ] DELETE /_matrix/client/r0/directory/room/{roomAlias}
- [ ] GET /_matrix/client/r0/directory/room/{roomAlias}

### Room Membership
- [ ] POST /_matrix/client/r0/rooms/{roomId}/invite
- [ ] POST /_matrix/client/r0/join/{roomIdOrAlias}
- [ ] POST /_matrix/client/r0/rooms/{roomId}/join
- [ ] POST /_matrix/client/r0/rooms/{roomId}/forget
- [ ] POST /_matrix/client/r0/rooms/{roomId}/leave
- [ ] POST /_matrix/client/r0/rooms/{roomId}/kick
- [ ] POST /_matrix/client/r0/rooms/{roomId}/unban
- [ ] POST /_matrix/client/r0/rooms/{roomId}/ban

### Room Tagging
- [ ] PUT /_matrix/client/r0/user/{userId}/rooms/{roomId}/tags/{tag}
- [ ] DELETE /_matrix/client/r0/user/{userId}/rooms/{roomId}/tags/{tag}
- [ ] GET /_matrix/client/r0/user/{userId}/rooms/{roomId}/tags

### Profiles
- [ ] PUT /_matrix/client/r0/profile/{userId}/displayname
- [ ] GET /_matrix/client/r0/profile/{userId}/displayname
- [ ] PUT /_matrix/client/r0/profile/{userId}/avatar_url
- [ ] GET /_matrix/client/r0/profile/{userId}/avatar_url
- [ ] GET /_matrix/client/r0/profile/{userId}

### Presence
- [ ] PUT /_matrix/client/r0/presence/{userId}/status
- [ ] GET /_matrix/client/r0/presence/{userId}/status
- [ ] POST /_matrix/client/r0/presence/list/{userId}
- [ ] GET /_matrix/client/r0/presence/list/{userId}

### Content Repository
- [ ] GET /_matrix/media/r0/download/{serverName}/{mediaId}
- [ ] POST /_matrix/media/r0/upload
- [ ] GET /_matrix/media/r0/thumbnail/{serverName}/{mediaId}

### VoIP
- [ ] GET /_matrix/client/r0/voip/turnServer

### Search
- [ ] POST /_matrix/client/r0/search

### Client Config
- [ ] PUT /_matrix/client/r0/user/{userId}/rooms/{roomId}/account_data/{type}
- [ ] PUT /_matrix/client/r0/user/{userId}/account_data/{type}

**Comment by NotAFile** [comment]
GET /_matrix/client/r0/rooms/{roomId}/members
 GET /_matrix/client/r0/rooms/{roomId}/messages

these exist now afaict, implemented by `client.JoinedMembers` and `client.Messages`
